export const PreviousSponsorLists = [
  {
    img: "/previous-sponsor/air-asia.png",
    alt: "Air Asia",
    link: "https://www.airasia.com",
    name: "Air Asia",
  },
  {
    img: "/previous-sponsor/amazon-web-service.png",
    alt: "Amazon Web Service",
    link: "https://aws.amazon.com",
    name: "Amazon Web Service",
  },
  {
    img: "/previous-sponsor/braintree.png",
    alt: "Braintree",
    link: "https://www.braintreepayments.com/my",
    name: "Braintree",
  },
  {
    img: "/previous-sponsor/cmscom.png",
    alt: "CMScom",
    link: "https://www.cmscom.jp",
    name: "CMScom",
  },
  {
    img: "/previous-sponsor/cytron-io.png",
    alt: "Cytron Technologies",
    link: "https://www.cytron.io",
    name: "Cytron Technologies",
  },
  {
    img: "/previous-sponsor/elastic-search.png",
    alt: "ElasticSearch",
    link: "https://www.elastic.co",
    name: "ElasticSearch",
  },
  {
    img: "/previous-sponsor/gandi-net.png",
    alt: "Gandi.net",
    link: "https://www.gandi.net",
    name: "Gandi.net",
  },
  {
    img: "/previous-sponsor/hennge.png",
    alt: "Hennge",
    link: "https://hennge.com",
    name: "Hennge",
  },
  {
    img: "/previous-sponsor/hitbseccon.png",
    alt: "HITB Security Conference",
    link: "https://conference.hitb.org/",
    name: "HITBSecCon",
  },
  {
    img: "/previous-sponsor/iumw.png",
    alt: "International University of Malaya-Wales",
    link: "https://www.iumw.edu.my/",
    name: "IUMW",
  },
  {
    img: "/previous-sponsor/jet-brains.png",
    alt: "JetBrains",
    link: "https://www.jetbrains.com",
    name: "JetBrains",
  },
  {
    img: "/previous-sponsor/jewel-paymentech.png",
    alt: "Jewel Paymentech",
    link: "https://www.jewelpaymentech.com/",
    name: "Jewel Paymentech",
  },
  {
    img: "/previous-sponsor/jublia.png",
    alt: "Jublia",
    link: "https://www.jublia.com/",
    name: "Jublia",
  },
  {
    img: "/previous-sponsor/lazada.png",
    alt: "Lazada",
    link: "https://www.lazada.com.my/",
    name: "Lazada",
  },
  {
    img: "/previous-sponsor/mesa.png",
    alt: "Malaya Electrical Students Association",
    link: "https://mesa-um.github.io/",
    name: "MESA",
  },
  {
    img: "/previous-sponsor/microsoft.png",
    alt: "Microsoft",
    link: "https://www.microsoft.com",
    name: "Microsoft",
  },
  {
    img: "/previous-sponsor/mindvalley.png",
    alt: "Mindvalley",
    link: "https://www.mindvalley.com/",
    name: "Mindvalley",
  },
  {
    img: "/previous-sponsor/oreilly.png",
    alt: "O'reilly",
    link: "https://www.oreilly.com/",
    name: "O'reilly",
  },
  {
    img: "/previous-sponsor/pyconjp.png",
    alt: "PyCon Japan",
    link: "https://www.pycon.jp/",
    name: "PyCon Japan",
  },
  {
    img: "/previous-sponsor/psf.png",
    alt: "Python Software Foundation",
    link: "https://www.python.org/psf-landing/",
    name: "PSF",
  },
  {
    img: "/previous-sponsor/pugs.png",
    alt: "Python User Group Singapore",
    link: "https://pugs.org.sg/",
    name: "PUG Singapore",
  },
  {
    img: "https://placehold.co/600x400/png",
    alt: "Shoppr Labs",
    link: "https://www.facebook.com/joinshoppr/",
    name: "Shoppr Labs",
  },
  {
    img: "/previous-sponsor/squeeze-inc.png",
    alt: "Squeeze Inc",
    link: "https://squeeze-inc.co.jp/",
    name: "Squeeze Inc",
  },
  {
    img: "https://placehold.co/600x400/png",
    alt: "Solution X",
    link: "https://www.solutionx.com.my/",
    name: "Solution X",
  },
  {
    img: "/previous-sponsor/tezos.png",
    alt: "Tezos",
    link: "https://tezos.com/",
    name: "Tezos",
  },
  {
    img: "/previous-sponsor/twilio.png",
    alt: "Twilio",
    link: "https://www.twilio.com",
    name: "Twilio",
  },
  {
    img: "/previous-sponsor/um.png",
    alt: "Universiti Malaya",
    link: "https://www.um.edu.my/",
    name: "Universiti Malaya",
  },
  {
    img: "/previous-sponsor/virtuozzo.png",
    alt: "Virtuozzo",
    link: "https://www.virtuozzo.com/",
    name: "Virtuozzo",
  },
  {
    img: "/previous-sponsor/vitrox.png",
    alt: "ViTrox",
    link: "https://www.vitrox.com/",
    name: "ViTrox",
  },
  {
    img: "/previous-sponsor/vonage.png",
    alt: "Vonage",
    link: "https://www.vonage.com.my/",
    name: "Vonage",
  },
  {
    img: "/previous-sponsor/xoxzo.png",
    alt: "Xoxzo",
    link: "https://www.xoxzo.com/en/",
    name: "Xoxzo",
  },
];
